rename project and repos
openinfradev/decapod-bootstrap pull request #1
Opened 2021-07-16 07:25 UTC by robertchoi80

renaming과 namespace 변경 등 플래닝 때 피드백 받은 내용들 수정.

2021-07-16 07:45 UTC, bluejayA requested changes

2021-07-16 07:45 UTC, bluejayA commented on decapod-apps/postgres.yaml
> +  namespace: db
namespace로 db는 너무 generic 해서, 좀 더 specific한 이름이면 좋을 듯 합니다. 

용도는 tks에서 사용하는 shared db 용도이므로, tks-db 는 어떨까요?

2021-07-16 07:53 UTC, robertchoi80 commented on decapod-apps/postgres.yaml
> +  namespace: db
네 저도 처음에 그렇게 생각했는데, 이 내용을 구축형에서도 사용하려면 'tks' 로 한정짓지 않는게 좋지 않을까 해서요.  혹시 구축형 상품도 tks라는 명칭을 사용하나요?

2021-07-16 08:10 UTC, bluejayA commented on decapod-apps/postgres.yaml
> +  namespace: db
그럼 아예 decapod-db 라고 하는건 어떠세요?
keycloak 이 사용을 하지만,  뭐, decapod로 설치되는 애들이 쓰는 db라는 뜻도 되지 않을까 해서

2021-07-16 11:07 UTC, robertchoi80 commented on decapod-apps/postgres.yaml
> +  namespace: db
네 그럼 일단 그렇게 하겠습니다. 사실 의견 중에 나중에 다른 db나 비슷한 성격을 가진 녀석들을 이 namespace에 몰아넣자는 의견도 있었는데, 그때 필요하면 다시 조정하면 되니까요

2021-07-19 07:03 UTC, zugwan approved these changes

2021-07-19 07:04 UTC, bluejayA approved these changes

2021-07-19 07:11 UTC, merged