add README
openinfradev/decapod-bootstrap pull request #2
Opened 2021-07-21 09:11 UTC by robertchoi80

documentation 초기 버전 작성

2021-07-21 13:49 UTC, Jaesang requested changes

2021-07-21 13:49 UTC, Jaesang commented on README.md
> +$ helm install argo-cd argo/argo-cd --version 3.9.0 -f ./decapod-bootstrap/argocd-install/values-override.yaml
namespace argo `-n argo`를 붙여줘야 정상적으로 실행이 되었습니다. (미적용 시 `default`네임스페이스에 설치되고, `decapod-apps`, `decapod-projects` 도 수행안됨)

2021-07-21 13:49 UTC, Jaesang commented on README.md
> +### Watch for applications to bootstrap automatically
argo-workflow-operator 실행 시 에러가 발생합니다.
```
$ kubectl logs -n argo argo-workflows-operator-workflow-controller-5698d77d76-ncb84
...
time="2021-07-21T13:45:38.377Z" level=fatal msg="Failed to update config: dial tcp: lookup postgresql.argo on 10.43.0.10:53: no such host"
```

2021-07-22 00:57 UTC, robertchoi80 commented on README.md
> +### Watch for applications to bootstrap automatically
네 이부분은 https://github.com/openinfradev/decapod-base-yaml/pull/103 가 먼저 merge되어야 합니다

2021-07-22 01:03 UTC, robertchoi80 commented on README.md
> +$ helm install argo-cd argo/argo-cd --version 3.9.0 -f ./decapod-bootstrap/argocd-install/values-override.yaml
수정하였습니다

2021-07-22 02:47 UTC, Jaesang commented on README.md
> +### Watch for applications to bootstrap automatically
decapod-base-yaml merge가 되어 돌려보았는데, argocd의 decapod-db-secret에서 아래 에러가 발생합니다.
```
rpc error: code = Unknown desc = hanu-reference/decapod-controller/decapod-db-secret: app path does not exist
```
prepare-decapod-controller에서도 동일한 에러가 발생합니다.
```
rpc error: code = Unknown desc = Manifest generation error (cached): hanu-reference/decapod-controller/prepare-decapod-controller: app path does not exist
```
 위 에러로 인해 decapod-db namespace에 secret이 생성되지 않아, postgresql이 정상실행되지 않고있습니다.
```
ubuntu@ubuntu-dev-2004:~$ kubectl get po -n decapod-db
NAME                      READY   STATUS                       RESTARTS   AGE
postgresql-postgresql-0   0/1     CreateContainerConfigError   0          10m
```

2021-07-22 03:08 UTC, robertchoi80 commented on README.md
> +### Watch for applications to bootstrap automatically
app name 수정하였습니다

2021-07-22 03:57 UTC, seungkyua commented
postgresql 은 decapod-db namespace 에 생성되는 것은 아닌가요?

2021-07-22 04:25 UTC, robertchoi80 commented
> postgresql 은 decapod-db namespace 에 생성되는 것은 아닌가요?

네 맞습니다. 혹시 재상님 코멘트 말씀하시는 거라면 거기서 namespace 지정한 건 argocd 자체의 namespace라서 postgresql 과는 관계 없습니다

2021-07-23 00:10 UTC, Jaesang approved these changes

2021-07-23 00:42 UTC, zugwan approved these changes

2021-07-23 00:46 UTC, zugwan requested changes
https://github.com/openinfradev/decapod-bootstrap/commit/c11e3ae921b652226e8e396ab20ec11d4cca659a 내용과 충돌이 있습니다. 수정이 필요합니다.

2021-07-23 05:29 UTC, robertchoi80 commented
> [c11e3ae](https://github.com/openinfradev/decapod-bootstrap/commit/c11e3ae921b652226e8e396ab20ec11d4cca659a) 내용과 충돌이 있습니다. 수정이 필요합니다.

성일님께 말씀드리고 main 브랜치의 커밋을 원복하였습니다.

2021-07-23 05:45 UTC, merged