TACODEV-774: enable metric on argo series
openinfradev/decapod-bootstrap pull request #3
Opened 2021-07-22 12:17 UTC by intelliguy

2021-07-23 14:01 UTC, Jaesang requested changes

2021-07-23 14:01 UTC, Jaesang commented on argocd-install/values-override.yaml
> +    type: LoadBalancer
변경 이유는 무엇인가요?

2021-07-23 14:01 UTC, Jaesang commented on decapod-apps/argo-secret.yaml
> +apiVersion: argoproj.io/v1alpha1
이미 반영된 부분 같습니다.

2021-07-23 14:01 UTC, Jaesang commented on decapod-apps/decapod-db-secret.yaml
> +    path: hanu-reference/decapod-controller/db-secret-decapod-db
이미 반영된 부분 같습니다.

2021-07-29 01:13 UTC, robertchoi80 commented
@intelliguy 재상님 리뷰 후, follow-up이 안되고 있습니다

2021-08-11 01:23 UTC, intelliguy commented on argocd-install/values-override.yaml
> +    type: LoadBalancer
외부 접근을 위해 사용했었는데 원복할 예정입니다.

2021-08-26 02:33 UTC, Jaesang approved these changes

2021-09-03 00:07 UTC, merged