TACODEV-774: enable metric on argo series
openinfradev/decapod-bootstrap pull request #6
Opened 2021-09-03 08:24 UTC by intelliguy

reverted merge 
- https://github.com/openinfradev/decapod-bootstrap/pull/3
- remove bugfix

2021-09-03 08:26 UTC, robertchoi80 commented on argocd-install/values-override.yaml
> +redis-ha.haproxy.metrics.enabled:
이 라인은 값이 안 들어있습니다

2021-09-03 08:33 UTC, intelliguy commented on argocd-install/values-override.yaml
> +redis-ha.haproxy.metrics.enabled:
다시 올렸어요

2021-09-03 11:41 UTC, zugwan requested changes

2021-09-03 11:41 UTC, zugwan commented on argocd-install/values-override.yaml
> +  metrics.enabled: true
이 부분도 오류 아닌가요? server.metrics.enabled 의 오타가 아닌가 싶습니다. 확인 부탁 드립니다.

2021-10-06 03:11 UTC, intelliguy commented on argocd-install/values-override.yaml
> +  metrics.enabled: true
1라인에 server가 있고 이후 metrics.enabled가 있으므로 이 값이 server.metrics.enabled  입니다.

2021-10-06 08:16 UTC, zugwan commented on argocd-install/values-override.yaml
> +  metrics.enabled: true
아래 추가된 값들이 한 줄로 되어있어 오해를 했었네요. 일관성 맞추는 관점에서 추가하신 내용들을 한 줄이 아닌 블록으로 하는 것이 좋을 듯 합니다.

2021-10-07 06:03 UTC, intelliguy commented on argocd-install/values-override.yaml
> +  metrics.enabled: true
수정했습니다.

2021-10-07 06:15 UTC, Jaesang requested changes

2021-10-07 06:15 UTC, Jaesang commented on argocd-install/values-override.yaml
> +dex.metrics.enabled: true
위 metrics.enabled처럼
```
dex:
  metrics:
    enabled: true 
```
와 같이 

통일을 하는게 좋아보입니당

2021-10-07 06:21 UTC, intelliguy commented on argocd-install/values-override.yaml
> +dex.metrics.enabled: true
https://github.com/openinfradev/decapod-base-yaml/blob/main/lma/base/site-values.yaml 와 같이 기본적으로 
'aaa.aaa.aaa: value' 형태로 valueoverride를 하고 있었습니다.
위에는 블록에서 헛갈릴수 있을꺼 같아서 반영했습니다.
제안하신 형태로 수정한다면 (원 파일의) 아래에 정의된 값들도 모두 바꿔야 하고 한줄이 여러줄로 변경되어 훨씬 긴 파일을 유지해야합니다.
추가로 yaml에서 인덴트가 정확하게 보이지 않아서 개인적으로는 선호하지 않습니다.

2021-10-07 06:41 UTC, Jaesang commented on argocd-install/values-override.yaml
> +dex.metrics.enabled: true
decapod site-values.yaml에서는 그렇게 하는게 룰이니 말씀하신게 맞습니다.
이 파일에서는 위 `server:` 처럼 그 형태를 같이 하는게 맞지않을까요?

2021-10-07 06:43 UTC, Jaesang approved these changes

2021-10-07 06:59 UTC, intelliguy commented on argocd-install/values-override.yaml
> +dex.metrics.enabled: true
앞에 밝힌 이유로 더 좋은 표현방식으로 보이지는 않습니다.
또한 valueoverride를 위한 값의 정의이기도 하고요.
이 표현방법에 대해서는 논의를 해보시지요. 
건별 선택보다는 룰을 정해서 가는게 좋겠습니다.

2021-10-07 07:34 UTC, zugwan requested changes

2021-10-07 07:34 UTC, zugwan commented on argocd-install/values-override.yaml
> +dex.metrics.enabled: true
2 가지 표현 형식이 모두 가능하더라도 단일 파일 내에서는 하나의 표현 방식으로 가는게 바람직해 보입니다.

2021-10-07 07:58 UTC, robertchoi80 commented on argocd-install/values-override.yaml
> +dex.metrics.enabled: true
좀 애매한 케이스네요. 지금 형태는 일관성이 없어보이긴 해서 사실 통일된 형태로 작성하는데 맞긴 한데,, 만약 단일 값 override 때문에 세 라인씩 인덴트 넣어가며 작성하는게 큰 오버헤드처럼 느껴진다면, 중재안으로 ## 같은 주석으로 섹션 구분하는 느낌으로 처리하는 건 어떨까요??  그냥 즉흥적인 아이디어라서,  동의하는 분이 많지 않으면 그냥 전부 통일하는 방향으로 가구요.
```
server:
  key1:
     key2
      ...

######################################
# Simple one-line variable overrides #
######################################
xx.enabled: true
yy.enabled: true
...
```

2021-10-07 08:34 UTC, intelliguy commented on argocd-install/values-override.yaml
> +dex.metrics.enabled: true
논의는 https://github.com/openinfradev/tks-issues/issues/30 에서 히스토리가 남을수 있게 진행하시는게 좋아보입니다.

2021-10-07 08:35 UTC, intelliguy commented on argocd-install/values-override.yaml
> +dex.metrics.enabled: true
이건 닫히면 찾기 힘들어서

2021-10-08 04:58 UTC, merged