구축 사이트 별 환경 설정을 위한 수정
openinfradev/decapod-bootstrap pull request #7
Opened 2021-11-09 07:04 UTC by zugwan

온라인/오프라인, 내부 git 저장소 운영 등 구축 사이트 별 환경에 대응하기 위해 아래 3가지 항목을 설정 가능토록 하고 최종 yaml 파일들을 생성하도록 (genereate_yamls.sh) 수정하였습니다.
- DECAPOD_SITE_NAME="hanu-reference"
- DECAPOD_BOOTSTRAP_GIT_REPO_URL="https://github.com/openinfradev/decapod-bootstrap.git"
- DECAPOD_MANIFESTS_GIT_REPO_URL="https://github.com/openinfradev/decapod-manifests.git"

2021-11-09 07:16 UTC, Jaesang requested changes

2021-11-09 07:16 UTC, Jaesang commented on genereate_yamls.sh
> +ARGS=$(getopt -o 's:b:m:h' --long 'site:,bootstrap-git:,manifests-git:,help' -- "$@") || usage
스크립트 실행 시 아무 메시지가 표시 되지 않는데, usage가 표시되면 좋겠습니다.

2021-11-09 07:34 UTC, zugwan commented on genereate_yamls.sh
> +ARGS=$(getopt -o 's:b:m:h' --long 'site:,bootstrap-git:,manifests-git:,help' -- "$@") || usage
파라미터 없이 실행 시 기본 설정에 따라 YAML 생성하도록 했었습니다. 아래처럼 메세지를 추가했는데 어떠신가요?
 ``` 
./genereate_yamls.sh 
=== Create YAML files using the following Decapod configuration. For help, use the '-h' option
 Site: hanu-reference
 Bootstrap Git: https://github.com/openinfradev/decapod-bootstrap.git
 Manifests Git: https://github.com/openinfradev/decapod-manifests.git
```

2021-11-09 07:43 UTC, Jaesang commented on genereate_yamls.sh
> +ARGS=$(getopt -o 's:b:m:h' --long 'site:,bootstrap-git:,manifests-git:,help' -- "$@") || usage
네, 좋네요, 이해하는데 큰 무리 없습니다

2021-11-09 07:44 UTC, Jaesang approved these changes

2021-11-10 01:28 UTC, robertchoi80 commented
이 내용이 각 환경변수에 repo url 등 값 넣어주고, template-OOO 파일을 OOO 파일로 치환만 해주는 거죠?  파일 내의 환경변수 자체가 실제 값으로 치환되는 건 아니고..  제가 이해한게 맞나요?

2021-11-10 01:31 UTC, zugwan commented
> 이 내용이 각 환경변수에 repo url 등 값 넣어주고, template-OOO 파일을 OOO 파일로 (파일명만) 치환해주는 거죠? 파일 내의 환경변수 자체가 실제 값으로 치환되는 건 아니고.. 제가 이해한게 맞나요?

네, genereate_yamls.sh 에서 입력받은 파라미터를 환경 변수로 생성하고 template-* 으로부터 실제 yaml 파일을 생성하도록 한 것입니다. 기본 yaml 파일은 현재 값 그대로 입니다.

2021-11-10 02:06 UTC, robertchoi80 approved these changes

2021-11-10 02:07 UTC, merged